/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author asus
 */
public class VerSBaby extends javax.swing.JFrame {

    /**
     * Creates new form VerSBaby
     */
    public VerSBaby() {
        initComponents();
             //AJUSTAMOS UNA IMAGEN A UN LABEL
        ImageIcon imagen = new ImageIcon("src/Imagenes/Tom.jpg");//Donde se encuentra la imagen
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(Perfil2.getWidth(),
                Perfil2.getHeight(), Image.SCALE_DEFAULT));//Asi ajustamos la imagen de acuerdo a los parametros del label
        Perfil2.setIcon(icono);//Lo enlazamos con el icono creado
       //SEGUNDA IMAGEN
        ImageIcon imagen2 = new ImageIcon("src/Imagenes/Cara.jpg");//Donde se encuentra la imagen
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(Perfil3.getWidth(),
                Perfil3.getHeight(), Image.SCALE_DEFAULT));//Asi ajustamos la imagen de acuerdo a los parametros del label
        Perfil3.setIcon(icono2);//Lo enlazamos con el icono creado
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Perfil1 = new javax.swing.JLabel();
        Perfil2 = new javax.swing.JLabel();
        Perfil3 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabel1.setText("Suggar Babys");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        Perfil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Chloe.jpg"))); // NOI18N
        Perfil1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Perfil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 210, 240));

        Perfil2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Perfil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 190, 230));

        Perfil3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Perfil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 190, 230));

        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Principañ.png"))); // NOI18N
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
          new Conti().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerSBaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerSBaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerSBaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerSBaby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerSBaby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Perfil1;
    private javax.swing.JLabel Perfil2;
    private javax.swing.JLabel Perfil3;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
